spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:bagnsave_db_v2}
spring.datasource.username=${DB_USER:bashServiceAccount}
spring.datasource.password=${DB_PASSWORD:temp}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
server.servlet.context-path=/api

